default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { Socket.gethostname rescue "localhost" == "db" ? "db" : "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

development:
  <<: *default
  database: onestep_now_development

test:
  <<: *default
  database: onestep_now_test

production:
  <<: *default
  database: onestep_now_production
