import avatarOne from './assets/avatars/avatar-1.svg'
import avatarTwo from './assets/avatars/avatar-2.svg'
import avatarThree from './assets/avatars/avatar-3.svg'
import avatarFour from './assets/avatars/avatar-4.svg'
import avatarFive from './assets/avatars/avatar-5.svg'
import avatarSix from './assets/avatars/avatar-6.svg'
import avatarSeven from './assets/avatars/avatar-7.svg'
import avatarEight from './assets/avatars/avatar-8.svg'
import type { FeedPost } from './appTypes'
import type { SignupForm } from './signupApi'

export const initialForm: SignupForm = {
  name: '',
  email: '',
  password: '',
  passwordConfirmation: '',
}

export const passwordGuidance = '8文字以上で英字と数字を含めてください'
export const passwordPattern = '(?=.*[A-Za-z])(?=.*\\d)[A-Za-z0-9]{8,}'
export const customPhotoIconId = 'custom-photo'
export const signupScreenStorageKey = 'onestep-signup-screen'
export const signupDraftStorageKey = 'onestep-signup-draft'
export const signupCompleteStorageKey = 'onestep-signup-complete'
export const authSessionStorageKey = 'onestep-auth-session'
export const avatarImageSize = 256
export const avatarImageQuality = 0.82
export const feedViewDurationSeconds = 3 * 60

export const sampleFeedPosts: Array<
  Omit<FeedPost, 'createdAt'> & { ageMinutes: number }
> = [
  {
    id: 'sample-1',
    userName: 'あや',
    level: 5,
    task: '参考記事を1つ読む',
    status: 'done',
    statusLabel: 'できた',
    likes: 120,
    commentsCount: 0,
    comments: [],
    ageMinutes: 1,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-2',
    userName: 'たろう',
    level: 20,
    task: '問題5問解く',
    status: 'doing',
    statusLabel: 'やります',
    likes: 1,
    commentsCount: 0,
    comments: [],
    ageMinutes: 3,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-3',
    userName: 'みき',
    level: 7,
    task: '洗い物をする',
    status: 'done',
    statusLabel: 'できた',
    likes: 12,
    commentsCount: 0,
    comments: [],
    ageMinutes: 4,
    liked: true,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-4',
    userName: 'けんじ',
    level: 1,
    task: 'バグを直す',
    status: 'doing',
    statusLabel: 'やります',
    likes: 2,
    commentsCount: 0,
    comments: [],
    ageMinutes: 7,
    liked: true,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-5',
    userName: 'はる',
    level: 16,
    task: '部屋を片付ける',
    status: 'done',
    statusLabel: 'できた',
    likes: 12,
    commentsCount: 0,
    comments: [],
    ageMinutes: 8,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-6',
    userName: 'ゆい',
    level: 9,
    task: 'ストレッチを5分する',
    status: 'doing',
    statusLabel: 'やります',
    likes: 4,
    commentsCount: 0,
    comments: [],
    ageMinutes: 10,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-7',
    userName: 'そうた',
    level: 12,
    task: '英単語を10個覚える',
    status: 'done',
    statusLabel: 'できた',
    likes: 8,
    commentsCount: 0,
    comments: [],
    ageMinutes: 12,
    liked: true,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-8',
    userName: 'りん',
    level: 3,
    task: '机の上を整理する',
    status: 'doing',
    statusLabel: 'やります',
    likes: 3,
    commentsCount: 0,
    comments: [],
    ageMinutes: 15,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-9',
    userName: 'なお',
    level: 18,
    task: 'メールを1件返信する',
    status: 'done',
    statusLabel: 'できた',
    likes: 15,
    commentsCount: 0,
    comments: [],
    ageMinutes: 18,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
  {
    id: 'sample-10',
    userName: 'まい',
    level: 6,
    task: '明日の予定を3つ書く',
    status: 'doing',
    statusLabel: 'やります',
    likes: 5,
    commentsCount: 0,
    comments: [],
    ageMinutes: 20,
    liked: false,
    commented: false,
    isOwnPost: false,
    canLike: true,
    canComment: true,
  },
]

export const avatarOptions = [
  { id: 'avatar-1', src: avatarOne, label: 'アイコン1' },
  { id: 'avatar-2', src: avatarTwo, label: 'アイコン2' },
  { id: 'avatar-3', src: avatarThree, label: 'アイコン3' },
  { id: 'avatar-4', src: avatarFour, label: 'アイコン4' },
  { id: 'avatar-5', src: avatarFive, label: 'アイコン5' },
  { id: 'avatar-6', src: avatarSix, label: 'アイコン6' },
  { id: 'avatar-7', src: avatarSeven, label: 'アイコン7' },
  { id: 'avatar-8', src: avatarEight, label: 'アイコン8' },
  { id: customPhotoIconId, src: '', label: '選択した写真' },
]
